services:
  readsb:
    container_name: readsb
    devices:
    - /dev/bus/usb:/dev/bus/usb
    environment:
    - TZ=EST
    - READSB_DCFILTER=true
    - READSB_DEVICE_TYPE=rtlsdr
    - READSB_RTLSDR_DEVICE=0
    - READSB_FIX=true
    - READSB_GAIN=autogain
    - READSB_LAT=33.533746
    - READSB_LON=-82.130676
    - READSB_MODEAC=true
    - READSB_RX_LOCATION_ACCURACY=2
    - READSB_STATS_RANGE=true
    - READSB_NET_ENABLE=true
    #- READSB_NET_CONNECTOR=172.17.0.1,37982,beast_in
    hostname: readsb
    image: ghcr.io/sdr-enthusiasts/docker-readsb-protobuf:latest
    ports:
    - 8080:8080
    - 30005:30005
    restart: always
    tmpfs:
    - /run/readsb:size=64M
    - /var/log:size=32M
    tty: true
    volumes:
    - readsbpb_rrd:/run/collectd
    - readsbpb_autogain:/run/autogain
    - /proc/diskstats:/proc/diskstats:ro
version: '2.0'
volumes:
  readsbpb_autogain: null
  readsbpb_rrd: null
