version: '3'

services:
  deflimongodb:
    build:
      context: https://github.com/alphafox02/docker-deflimongodb.git
    container_name: deflimongodb
    restart: unless-stopped
    labels:
      - "autoheal=true"
