services:
  readsb:
    container_name: readsb
    device_cgroup_rules:
    - 'c 189:* rwm'
    environment:
    - TZ="America/New_York"
    - READSB_DCFILTER=true
    - READSB_DEVICE_TYPE=rtlsdr
    - READSB_RTLSDR_DEVICE=0
    - READSB_FIX=true
    - READSB_GAIN=autogain
    - READSB_LAT=33.533746
    - READSB_LON=-82.130676
    - READSB_MODEAC=true
    - READSB_RX_LOCATION_ACCURACY=2
    - READSB_STATS_RANGE=true
    - READSB_NET_ENABLE=true
    - PROMETHEUS_ENABLE=true
    - TAR1090_ENABLE_AC_DB=true
    # Uncomment the below line to have dump978 make it into the tar1090 interface
    #- READSB_NET_CONNECTOR=172.17.0.1,37982,beast_in
    hostname: readsb
    image: ghcr.io/sdr-enthusiasts/docker-readsb-protobuf:telegraf
    ports:
    - 8080:8080
    - 30005:30005
    - 9273-9274:9273-9274
    restart: unless-stopped
    tmpfs:
    - /run/readsb:size=64M
    - /var/log:size=32M
    tty: true
    volumes:
    - readsbpb_rrd:/run/collectd
    - readsbpb_autogain:/run/autogain
    - /proc/diskstats:/proc/diskstats:ro
    - /dev:/dev:ro
version: '2.0'
volumes:
  readsbpb_autogain: null
  readsbpb_rrd: null
