version: '3'
services:
  dump978:
    image: ghcr.io/sdr-enthusiasts/docker-dump978:latest
    container_name: dump978
    ports:
      - "30978:30978"
      - "30979:30979"
      - "30980:80"
      - "37981:37981"
      - "37982:37982"
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    environment:
      - DUMP978_RTLSDR_DEVICE=00001090
      - DUMP978_SDR_GAIN=autogain
    restart: always
